---
- name: Using Collections
  hosts: all
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - name: Use a file lookup to import PEM Certificate
      f5networks.f5_modules.bigip_ssl_certificate:
        name: test
        state: present
        content: "{{ lookup('file', '{{ playbook_dir }}/server.crt') }}"
        validate_certs: no
        provider:
          server: "{{ inventory_hostname }}"
          user: admin
          password: f5te$t