---
- name: Using Collections
  hosts: all
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - name: Import both key and cert
      f5networks.f5_modules.bigip_ssl_key_cert:
        key_content: "{{ lookup('file', '{{ playbook_dir }}/key.pem') }}"
        key_name: test
        cert_content: "{{ lookup('file', '{{ playbook_dir }}/cert.pem') }}"
        cert_name: test
        state: present
        provider:
          password: f5te$t
          server: '{{ inventory_hostname }}'
          user: admin
          validate_certs: no

    - name: Add pool member
      bigip_pool_member:
        pool: my-pool
        partition: Common
        host: 192.168.1.1
        port: 80
        description: web server
        connection_limit: 100
        rate_limit: 50
        ratio: 2
        provider:
          server: '{{ inventory_hostname }}'
          user: admin
          password: f5te$t