---
- name: Using Collections
  hosts: all
  connection: local
  collections:
    - f5networks.f5_modules

  tasks:
    - name: Import both key and cert
      f5networks.f5modules.bigip_ssl_key_cert:
        key_content: "{{ lookup('file', '{{ playbook_dir }}/key.pem') }}"
        key_name: test
        cert_content: "{{ lookup('file', '{{ playbook_dir }}/cert.pem') }}"
        cert_name: test
        state: present
        provider:
          password: secret
          server: lb.mydomain.com
          user: admin
          validate_certs: no